version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"

  api:
    build: .
    command: bash -c "
        python manage.py migrate
        && python manage.py collectstatic --noinput
        && python manage.py runserver 0.0.0.0:8080"
    environment:
      STAGE: "0"
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./api:/api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
