# Generated by Django 2.2.8 on 2019-12-09 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20191021_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='payment_groups', through='api.GroupMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
