# Generated by Django 2.2.8 on 2019-12-10 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20191209_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'permissions': [('head', 'Can HEAD the endpoint'), ('options', 'Can OPTIONS the endpoint'), ('get', 'Can GET the endpoint'), ('patch', 'Can PATCH the endpoint'), ('post', 'Can POST, the endpoint'), ('put', 'Can PUT the endpoint'), ('delete', 'Can delete the endpoint')]},
        ),
    ]
