# Generated by Django 2.2.8 on 2019-12-10 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20191210_0442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmembership',
            options={},
        ),
    ]
