# Generated by Django 2.2.10 on 2020-05-14 14:48

import api.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200309_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payments', django.contrib.postgres.fields.jsonb.JSONField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Group')),
            ],
            bases=(models.Model, api.models.JsonizableMixin),
        ),
    ]
