# Generated by Django 2.2.10 on 2020-05-14 15:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
