# Generated by Django 2.2.10 on 2020-05-15 14:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20200514_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='curreny',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'USD')], default='EUR', max_length=4),
        ),
        migrations.AddField(
            model_name='payment',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
