# Generated by Django 2.2.10 on 2020-05-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20200515_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='target',
            field=models.EmailField(default='test@test.fr', max_length=254),
            preserve_default=False,
        ),
    ]
