# Generated by Django 2.2.10 on 2020-06-02 15:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='split.png', upload_to=api.models.get_icon_path),
        ),
    ]
