# Generated by Django 3.1 on 2020-11-19 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20201119_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pro',
            new_name='is_pro',
        ),
    ]
