name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build api
    - name: Run tests
      run: docker-compose run api python manage.py test
      
  update:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - uses: actions/checkout@v2
        name: Checkout Split repository
        with:
          repository: split2021/Split
          ref: pre-prod
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.SPLIT_BOT_TOKEN }}
      - name: Create merging branch
        run: git checkout -b "merge_${{ github.sha }}"
      - name: Update API submodule
        run: git submodule foreach git pull origin master
      - name: Add changes
        run: git add .
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Create pull request
        uses: peter-evans/create-pull-request@v2.7.1
        with:
          token: ${{ secrets.SPLIT_BOT_TOKEN }}
          title: "Update API to commit ${{ github.sha }}"
